##
## Kubernetes
##

[[constraint]]
  name = "k8s.io/apimachinery"
  branch = "release-1.10"

[[constraint]]
  name = "k8s.io/client-go"
  version = "7.0.0"

##
## 3rd Party
##

[[constraint]]
  name = "github.com/docopt/docopt-go"
  version = "0.6.2"

[prune]
  go-tests = true
  unused-packages = true
